---
layout: cv
title: Cole Parker's CV
---
# Cole Parker
**Business/Accounting Intern · Aspiring CPA**

## Education

`2020–2025`  
**Brigham Young University - Idaho**

- Bachelor of Science in Accounting  
- Certificate in Data Science  
- GPA: 3.95  
- Mentorship Officer, Student Accounting Society

## Awards

`2025`  
**Top Accounting Graduate**

## Experience

### Teaching Assistant  
**Brigham Young University - Idaho**  
*September 2021 – April 2025 · Rexburg, ID*  
Courses: ACCTG 205, ACCTG 233, ACCTG 401

- Helped students master key QuickBooks software functionalities  
- Provided detailed feedback and clarification on Excel models  
- Collaborated weekly with the instructor to foster an engaging learning environment

### Accounting Intern  
**Spudnik Equipment Co.**  
*July 2024 – September 2024 · Blackfoot, ID*

- Automated a dashboard tracking budgeted, actual, and forecasted monthly totals  
- Analyzed Balance Sheet and P&L statements over 2 years  
- Cleaned up 500+ vouchers payable accounts using Infor SyteLine (CloudSuite Industrial)

### Accounting Tutor (Managerial, Financial, Survey)  
**Brigham Young University - Idaho**  
*September 2023 – April 2024 · Rexburg, ID*

- Taught 50+ students with various learning styles  
- Diagnosed student errors and offered clear corrections  
- Provided feedback leading to a 10% increase in overall student performance

### Business Intern  
**Northern RNA Inc**  
*April 2023 – August 2023 · Calgary, AB*

- Troubleshot inventory issues on Business Dynamics 365  
- Recorded invoices and resolved discrepancies with AP clerks  
- Co-developed an inventory workflow system using Dynamics 365

## Volunteer Experience

### Full-Time Volunteer Representative  
**The Church of Jesus Christ of Latter-day Saints**  
*June 2019 – March 2020 · Montreal, QC*

- Adhered to a structured schedule involving diverse responsibilities  
- Worked in both team and solo environments, adapting every 6 weeks  
- Developed communication and interpersonal skills in high-pressure environments



<!-- ### Footer

Last updated: May 2013 -->